In [2]:
from tensorflow.keras.preprocessing.text import one_hot

In [3]:
### sentences
sent=[ 'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [4]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [5]:
### Vocabulary size
vocab_size = 10000

**One Hot Representation**

In [7]:
onehot_repr = [one_hot(words,vocab_size) for words in sent]
print(onehot_repr)

[[7457, 6593, 2947, 3760], [7457, 6593, 2947, 3755], [7457, 7650, 2947, 116], [1969, 8924, 6032, 8463, 1548], [1969, 8924, 6032, 8463, 7036], [2683, 7457, 1711, 2947, 5417], [246, 6616, 3843, 8463]]



**Word Embedding Represntation**

In [8]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [9]:
import numpy as np

In [10]:
sent_length = 8
embedded_docs = pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 7457 6593 2947 3760]
 [   0    0    0    0 7457 6593 2947 3755]
 [   0    0    0    0 7457 7650 2947  116]
 [   0    0    0 1969 8924 6032 8463 1548]
 [   0    0    0 1969 8924 6032 8463 7036]
 [   0    0    0 2683 7457 1711 2947 5417]
 [   0    0    0    0  246 6616 3843 8463]]


In [11]:
dim = 10

In [12]:
model = Sequential()
model.add(Embedding(vocab_size,10,input_length=sent_length))
model.compile('adam','mse')

In [13]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 8, 10)             100000    
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [14]:
print(model.predict(embedded_docs))

[[[ 0.0145441  -0.00147726 -0.0417679   0.04087498 -0.00470893
   -0.04606419  0.04637304  0.00544501 -0.0053449  -0.01740979]
  [ 0.0145441  -0.00147726 -0.0417679   0.04087498 -0.00470893
   -0.04606419  0.04637304  0.00544501 -0.0053449  -0.01740979]
  [ 0.0145441  -0.00147726 -0.0417679   0.04087498 -0.00470893
   -0.04606419  0.04637304  0.00544501 -0.0053449  -0.01740979]
  [ 0.0145441  -0.00147726 -0.0417679   0.04087498 -0.00470893
   -0.04606419  0.04637304  0.00544501 -0.0053449  -0.01740979]
  [-0.0447899   0.02389148 -0.01485892  0.01273846  0.01066775
    0.02196902  0.0224777  -0.02400602 -0.04864441  0.03421748]
  [-0.00859855  0.02485113  0.04791198 -0.02752184  0.04406993
    0.02656401 -0.04854287 -0.04094236 -0.01448641  0.01067996]
  [-0.01060339  0.02800148  0.00568449  0.02782467  0.04548944
    0.0083641  -0.0251834   0.04050018 -0.03091074  0.04354376]
  [ 0.01270627 -0.01370996  0.0307625  -0.03936002  0.02857244
   -0.01377685  0.01285661  0.0290756   0.003121

In [15]:
embedded_docs[0] ### First Sentence one hot encoding

array([   0,    0,    0,    0, 7457, 6593, 2947, 3760], dtype=int32)

In [17]:
print(model.predict(embedded_docs)[0]) ### Word Embedding for first sentence

[[ 0.0145441  -0.00147726 -0.0417679   0.04087498 -0.00470893 -0.04606419
   0.04637304  0.00544501 -0.0053449  -0.01740979]
 [ 0.0145441  -0.00147726 -0.0417679   0.04087498 -0.00470893 -0.04606419
   0.04637304  0.00544501 -0.0053449  -0.01740979]
 [ 0.0145441  -0.00147726 -0.0417679   0.04087498 -0.00470893 -0.04606419
   0.04637304  0.00544501 -0.0053449  -0.01740979]
 [ 0.0145441  -0.00147726 -0.0417679   0.04087498 -0.00470893 -0.04606419
   0.04637304  0.00544501 -0.0053449  -0.01740979]
 [-0.0447899   0.02389148 -0.01485892  0.01273846  0.01066775  0.02196902
   0.0224777  -0.02400602 -0.04864441  0.03421748]
 [-0.00859855  0.02485113  0.04791198 -0.02752184  0.04406993  0.02656401
  -0.04854287 -0.04094236 -0.01448641  0.01067996]
 [-0.01060339  0.02800148  0.00568449  0.02782467  0.04548944  0.0083641
  -0.0251834   0.04050018 -0.03091074  0.04354376]
 [ 0.01270627 -0.01370996  0.0307625  -0.03936002  0.02857244 -0.01377685
   0.01285661  0.0290756   0.00312113  0.02764403]]
